name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.6.2
  - cairo=1.18.0
  - expat=2.6.2
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - icu=73.2
  - krb5=1.21.2
  - lcms2=2.16
  - leptonica=1.83.1
  - lerc=4.0.0
  - libarchive=3.7.4
  - libcurl=8.8.0
  - libdeflate=1.20
  - libexpat=2.6.2
  - libffi=3.4.2
  - libglib=2.80.2
  - libiconv=1.17
  - libintl=0.22.5
  - libjpeg-turbo=3.0.0
  - libpng=1.6.43
  - libssh2=1.11.0
  - libtiff=4.6.0
  - libwebp=1.4.0
  - libwebp-base=1.4.0
  - libxml2=2.12.7
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - lzo=2.10
  - openjpeg=2.5.2
  - openssl=3.3.1
  - pcre2=10.44
  - pip=24.0
  - pixman=0.43.4
  - poppler=24.04.0
  - poppler-data=0.4.12
  - python=3.9.19
  - setuptools=69.5.1
  - sqlite=3.45.3
  - tesseract=5.4.1
  - tzdata=2024a
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.40.33810
  - vs2015_runtime=14.40.33810
  - wheel=0.43.0
  - xz=5.2.6
  - zlib=1.3.1
  - zstd=1.5.6
  - pip:
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - anthropic==0.29.0
      - anyio==4.4.0
      - async-timeout==4.0.3
      - attrs==23.2.0
      - certifi==2024.6.2
      - charset-normalizer==3.3.2
      - click==8.1.7
      - colorama==0.4.6
      - defusedxml==0.7.1
      - distro==1.9.0
      - dnspython==2.6.1
      - email-validator==2.2.0
      - exceptiongroup==1.2.1
      - fastapi==0.111.0
      - fastapi-cli==0.0.4
      - filelock==3.15.3
      - frozenlist==1.4.1
      - fsspec==2024.6.0
      - greenlet==3.0.3
      - h11==0.14.0
      - httpcore==1.0.5
      - httptools==0.6.1
      - httpx==0.27.0
      - httpx-sse==0.4.0
      - huggingface-hub==0.23.4
      - idna==3.7
      - jinja2==3.1.4
      - jiter==0.4.2
      - joblib==1.4.2
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - langchain==0.2.5
      - langchain-anthropic==0.1.15
      - langchain-core==0.2.9
      - langchain-mistralai==0.1.8
      - langchain-openai==0.1.8
      - langchain-text-splitters==0.2.1
      - langsmith==0.1.81
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - mdurl==0.1.2
      - multidict==6.0.5
      - numpy==1.26.4
      - openai==1.35.1
      - orjson==3.10.5
      - packaging==24.1
      - pdf2image==1.17.0
      - pillow==10.3.0
      - pydantic==2.7.4
      - pydantic-core==2.18.4
      - pygments==2.18.0
      - pytesseract==0.3.10
      - python-dotenv==1.0.1
      - python-multipart==0.0.9
      - pyyaml==6.0.1
      - regex==2024.5.15
      - requests==2.32.3
      - rich==13.7.1
      - scikit-learn==1.5.0
      - scipy==1.13.1
      - shellingham==1.5.4
      - sniffio==1.3.1
      - sqlalchemy==2.0.31
      - starlette==0.37.2
      - tenacity==8.4.1
      - threadpoolctl==3.5.0
      - tiktoken==0.7.0
      - tokenizers==0.19.1
      - tqdm==4.66.4
      - typer==0.12.3
      - typing-extensions==4.12.2
      - ujson==5.10.0
      - urllib3==2.2.2
      - uvicorn==0.30.1
      - watchfiles==0.22.0
      - websockets==12.0
      - yarl==1.9.4